#!/usr/bin/env python3
"""One-time, deterministic conversion of real MethylProphet/NTv3 artifacts into the
canonical rna_branch input contract (docs/rna_branch_experiments.md).

This script never touches third_party/MethylProphet, never touches
artifacts/genomic_encoder or artifacts/diagnostics (read-only), and never imports
methylation_predictor.genomic_encoder or methylation_predictor.diagnostics code
(rna_branch stays isolated from the genomic/diagnostics domains per PATCH_NOTES.md).
It only reads already-frozen, already-validated artifact files plus the raw
MethylProphetData release, and writes new files under an output directory.

Two model-fitting gaps are filled here, both by exactly replicating the frozen
recipe already used by genomic_encoder (Ridge(alpha=10) + 3-seed MLP
LayerNorm(d)-256-64-1 ensemble, StandardScaler fit on train only):

1. The NTv3 prior and the between/within-cancer variability heads never wrote
   predictions for TRAIN CpGs (only validation/test) because in-sample training
   predictions would leak. Train-CpG values are filled with 5-fold
   out-of-fold (OOF) predictions from the identical architecture/hyperparameters.
2. The variability heads never persisted per-CpG validation/test predictions at
   all (only aggregate metrics.json). Those are regenerated by refitting on the
   exact same train targets/embeddings and are checked for parity against the
   stored aggregate metrics.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import h5py
import numpy as np
import pandas as pd
import pyarrow.dataset as ds
import torch
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler

STR_DTYPE = h5py.string_dtype(encoding="utf-8")


def _str_array(values) -> np.ndarray:
    return np.asarray([str(v) for v in values], dtype=object)

# ---------------------------------------------------------------------------
# Fixed input locations (real artifacts already present on this machine).
# ---------------------------------------------------------------------------
REPO = Path(__file__).resolve().parents[3]
MP_DATA = Path("/data/dataset/methylation/MethylProphetData")

CPG_FEATURES = REPO / "artifacts/genomic_encoder/static_prior/tcga_val_cpg_static_features.parquet"
CPG_SPLIT_DIR = REPO / "artifacts/genomic_encoder/ntv3_prior/split_manifests"
EMBEDDINGS_NPZ = REPO / "artifacts/genomic_encoder/ntv3_prior/650M_post_embeddings/NTv3_650M_post_L32768_forward.npz"
PRIOR_VAL_TEST = REPO / "artifacts/genomic_encoder/ntv3_prior/final_NTv3_650M_post/NTv3_650M_post_L32768_centre_forward/locus_predictions.parquet"
VARIABILITY_TARGETS = REPO / "artifacts/genomic_encoder/ntv3_variability_final/block_validation/train_only_variance_targets.parquet"
BETWEEN_METRICS = REPO / "artifacts/genomic_encoder/ntv3_variability_components/between_block/metrics.json"
WITHIN_METRICS = REPO / "artifacts/genomic_encoder/ntv3_variability_components/within_block/metrics.json"

SAMPLE_CANCER_TYPE = REPO / "artifacts/diagnostics/methylprophet/locus_dominance/tcga_metadata/sample_idx_cancer_type.parquet"
OFFICIAL_TRAIN_SAMPLES = MP_DATA / "parquet/241231-tcga_array/metadata/subset_sample_split/ind_cancer/train_sample_tissue_count_with_idx.csv"
OFFICIAL_VAL_SAMPLES = MP_DATA / "parquet/241231-tcga_array/metadata/subset_sample_split/ind_cancer/val_sample_tissue_count_with_idx.csv"
GENE_EXPR = MP_DATA / "processed/241231-tcga_array-index_files-ind_cancer/gene_expr.filtered.parquet"
ME_CPG_BG_DIRS = [
    MP_DATA / "processed/241231-tcga_array-index_files-ind_cancer/me_cpg_bg/train_cpg-train_sample.parquet",
    MP_DATA / "processed/241231-tcga_array-index_files-ind_cancer/me_cpg_bg/train_cpg-val_sample.parquet",
    MP_DATA / "processed/241231-tcga_array-index_files-ind_cancer/me_cpg_bg/val_cpg-train_sample.parquet",
    MP_DATA / "processed/241231-tcga_array-index_files-ind_cancer/me_cpg_bg/val_cpg-val_sample.parquet",
]

MLP_HIDDEN = (256, 64)
MLP_SEEDS = (17, 29, 43)
MLP_EPOCHS = 500
MLP_LR = 1e-3
MLP_WD = 1e-4
MLP_DROPOUT = 0.1
OOF_FOLDS = 5
OOF_FOLD_SEED = 20260729
SAMPLE_VAL_TEST_SPLIT_SEED = 20260729


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _logit(x: np.ndarray, eps: float = 1e-6) -> np.ndarray:
    x = np.clip(x, eps, 1 - eps)
    return np.log(x) - np.log1p(-x)


class MLP(torch.nn.Module):
    def __init__(self, d: int, dropout: float):
        super().__init__()
        self.net = torch.nn.Sequential(
            torch.nn.LayerNorm(d),
            torch.nn.Linear(d, MLP_HIDDEN[0]),
            torch.nn.GELU(),
            torch.nn.Dropout(dropout),
            torch.nn.Linear(MLP_HIDDEN[0], MLP_HIDDEN[1]),
            torch.nn.GELU(),
            torch.nn.Linear(MLP_HIDDEN[1], 1),
        )

    def forward(self, x):
        return self.net(x).squeeze(-1)


def _fit_mlp(x_train, y_train, x_other, seed, device):
    torch.manual_seed(seed)
    np.random.seed(seed)
    model = MLP(x_train.shape[1], MLP_DROPOUT).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=MLP_LR, weight_decay=MLP_WD)
    x = torch.tensor(x_train, device=device)
    y = torch.tensor(y_train.astype(np.float32), device=device)
    for _ in range(MLP_EPOCHS):
        model.train()
        opt.zero_grad()
        torch.nn.functional.mse_loss(model(x), y).backward()
        opt.step()
    model.eval()
    with torch.inference_mode():
        return model(torch.tensor(x_other, device=device)).cpu().numpy()


def _mlp_ensemble_predict(x_train, y_train, x_other, device):
    """Mean of 3-seed MLP predictions, each already in the model's own space."""
    preds = [_fit_mlp(x_train, y_train, x_other, seed, device) for seed in MLP_SEEDS]
    return np.mean(preds, axis=0)


def _oof_ensemble(embeddings, target_logit, device, folds=OOF_FOLDS, fold_seed=OOF_FOLD_SEED):
    """5-fold out-of-fold MLP-ensemble predictions (beta space) for train-only CpGs."""
    n = len(target_logit)
    oof_logit = np.full(n, np.nan, dtype=np.float64)
    splitter = KFold(n_splits=folds, shuffle=True, random_state=fold_seed)
    for fold_index, (fit_idx, hold_idx) in enumerate(splitter.split(np.arange(n))):
        scaler = StandardScaler().fit(embeddings[fit_idx])
        x_fit = scaler.transform(embeddings[fit_idx])
        x_hold = scaler.transform(embeddings[hold_idx])
        pred = _mlp_ensemble_predict(x_fit, target_logit[fit_idx], x_hold, device)
        oof_logit[hold_idx] = pred
        print(f"    fold {fold_index + 1}/{folds} done", flush=True)
    if np.isnan(oof_logit).any():
        raise ValueError("OOF predictions left NaN holes")
    return oof_logit


@dataclass
class Metrics:
    mse: float
    spearman: float
    pearson: float


def _report_metrics(y, p) -> Metrics:
    from scipy.stats import pearsonr, spearmanr

    return Metrics(
        mse=float(np.mean((y - p) ** 2)),
        spearman=float(spearmanr(y, p).statistic),
        pearson=float(pearsonr(y, p).statistic),
    )


def build_cpg_universe() -> pd.DataFrame:
    frame = pd.read_parquet(CPG_FEATURES, columns=["cpg_idx", "chromosome", "position", "mean_train"])
    if (frame.chromosome != "chr1").any():
        raise ValueError("expected chr1-only CpG universe")
    if frame.cpg_idx.duplicated().any():
        raise ValueError("duplicate cpg_idx in CpG universe")
    return frame.reset_index(drop=True)


def build_cpg_splits(universe: pd.DataFrame) -> pd.DataFrame:
    parts = []
    for split in ("train", "validation", "test"):
        part = pd.read_parquet(CPG_SPLIT_DIR / f"{split}_cpg_manifest.parquet")
        part = part[["cpg_idx"]].copy()
        part["split"] = split
        parts.append(part)
    splits = pd.concat(parts, ignore_index=True)
    if splits.cpg_idx.duplicated().any():
        raise ValueError("a CpG appears in more than one split")
    if set(splits.cpg_idx) != set(universe.cpg_idx):
        raise ValueError("cpg split manifests do not cover the exact CpG universe")
    return splits


def load_embeddings(cpg_idx: np.ndarray) -> np.ndarray:
    with np.load(EMBEDDINGS_NPZ) as data:
        ids = data["cpg_idx"].astype(np.int64)
        centre = data["centre"].astype(np.float32)
    position = {cpg: row for row, cpg in enumerate(ids.tolist())}
    missing = [c for c in cpg_idx if c not in position]
    if missing:
        raise ValueError(f"{len(missing)} CpGs missing NTv3 embeddings")
    rows = np.asarray([position[c] for c in cpg_idx], dtype=np.int64)
    return centre[rows]


def build_prior(universe: pd.DataFrame, splits: pd.DataFrame, embeddings: np.ndarray, device: str) -> tuple[pd.Series, dict]:
    frame = universe.merge(splits, on="cpg_idx", validate="one_to_one")
    order = {cpg: row for row, cpg in enumerate(universe.cpg_idx.tolist())}
    pred = np.full(len(universe), np.nan, dtype=np.float64)

    frozen = pd.read_parquet(PRIOR_VAL_TEST, columns=["cpg_idx", "split", "pred_mlp_ensemble"])
    frozen_val_test = frame[frame.split.isin(["validation", "test"])]
    if set(frozen.cpg_idx) != set(frozen_val_test.cpg_idx):
        raise ValueError("frozen prior predictions do not match validation/test CpG universe")
    for cpg, value in zip(frozen.cpg_idx, frozen.pred_mlp_ensemble):
        pred[order[int(cpg)]] = value

    train_mask = frame.split.eq("train")
    train_frame = frame[train_mask].reset_index(drop=True)
    train_rows = np.asarray([order[c] for c in train_frame.cpg_idx], dtype=np.int64)
    train_embeddings = embeddings[train_rows]
    train_target_logit = _logit(train_frame.mean_train.to_numpy(np.float64))
    print("  [prior] fitting 5-fold OOF ensemble for train CpGs...", flush=True)
    oof_logit = _oof_ensemble(train_embeddings, train_target_logit, device)
    oof_beta = 1.0 / (1.0 + np.exp(-oof_logit))
    pred[train_rows] = oof_beta

    if np.isnan(pred).any():
        raise ValueError("prior prediction has unfilled CpGs")
    provenance = {
        "validation_test": {"source": str(PRIOR_VAL_TEST), "n": int(len(frozen)), "reused_frozen": True},
        "train": {"n": int(len(train_frame)), "method": f"{OOF_FOLDS}-fold OOF MLP ensemble (seeds {MLP_SEEDS})"},
    }
    return pd.Series(pred, index=universe.cpg_idx, name="pred_ntv3_prior"), provenance


def build_variability_component(
    universe: pd.DataFrame, splits: pd.DataFrame, embeddings: np.ndarray, targets: pd.DataFrame,
    component: str, stored_metrics_path: Path, device: str,
) -> tuple[pd.Series, dict]:
    frame = universe.merge(splits, on="cpg_idx", validate="one_to_one").merge(
        targets[["cpg_idx", f"{component}_variance"]], on="cpg_idx", validate="one_to_one"
    )
    frame[f"log_{component}"] = np.log(frame[f"{component}_variance"] + 1e-8)
    order = {cpg: row for row, cpg in enumerate(universe.cpg_idx.tolist())}
    pred = np.full(len(universe), np.nan, dtype=np.float64)

    train_mask = frame.split.eq("train")
    train_frame = frame[train_mask].reset_index(drop=True)
    other_frame = frame[~train_mask].reset_index(drop=True)
    train_rows = np.asarray([order[c] for c in train_frame.cpg_idx], dtype=np.int64)
    other_rows = np.asarray([order[c] for c in other_frame.cpg_idx], dtype=np.int64)
    train_embeddings = embeddings[train_rows]
    other_embeddings = embeddings[other_rows]
    y_train = train_frame[f"log_{component}"].to_numpy(np.float64)

    print(f"  [{component}] refitting ensemble on train, predicting validation+test...", flush=True)
    scaler = StandardScaler().fit(train_embeddings)
    x_train = scaler.transform(train_embeddings)
    x_other = scaler.transform(other_embeddings)
    other_pred = _mlp_ensemble_predict(x_train, y_train, x_other, device)
    pred[other_rows] = other_pred

    validation_mask = other_frame.split.eq("validation").to_numpy()
    parity = None
    if stored_metrics_path.exists() and validation_mask.any():
        stored = json.loads(stored_metrics_path.read_text())
        recomputed = _report_metrics(other_frame.loc[validation_mask, f"log_{component}"].to_numpy(), other_pred[validation_mask])
        stored_ensemble = stored["validation"].get("mlp_ensemble", stored["validation"].get("ridge"))
        parity = {
            "stored_validation_mse": stored_ensemble["mse_log_variance"],
            "recomputed_validation_mse": recomputed.mse,
            "stored_validation_spearman": stored_ensemble["spearman"],
            "recomputed_validation_spearman": recomputed.spearman,
        }

    print(f"  [{component}] fitting 5-fold OOF ensemble for train CpGs...", flush=True)
    oof = _oof_ensemble(train_embeddings, y_train, device)
    pred[train_rows] = oof

    if np.isnan(pred).any():
        raise ValueError(f"{component} prediction has unfilled CpGs")
    provenance = {
        "validation_test": {"n": int(len(other_frame)), "method": "refit ridge/mlp ensemble on train, predict held-out", "parity_check": parity},
        "train": {"n": int(len(train_frame)), "method": f"{OOF_FOLDS}-fold OOF MLP ensemble (seeds {MLP_SEEDS})"},
    }
    return pd.Series(pred, index=universe.cpg_idx, name=f"pred_log_var_{component.replace('_cancer', '')}"), provenance


def build_sample_universe() -> pd.DataFrame:
    cancer = pd.read_parquet(SAMPLE_CANCER_TYPE, columns=["sample_idx", "sample_name", "cancer_type"]).set_index("sample_idx")
    train_ids = pd.read_csv(OFFICIAL_TRAIN_SAMPLES)["sample_idx"].astype(int)
    val_ids = pd.read_csv(OFFICIAL_VAL_SAMPLES)["sample_idx"].astype(int)
    if set(train_ids) & set(val_ids):
        raise ValueError("official train/val sample splits overlap")

    train = cancer.loc[train_ids]
    train = train[train.cancer_type != "NA"].copy()
    train["split"] = "train"

    held_out = cancer.loc[val_ids]
    held_out = held_out[held_out.cancer_type != "NA"].copy()

    rng = np.random.default_rng(SAMPLE_VAL_TEST_SPLIT_SEED)
    held_out = held_out.reset_index()
    assignment = pd.Series(index=held_out.index, dtype=object)
    for cancer_type, group in held_out.groupby("cancer_type"):
        idx = group.index.to_numpy()
        rng.shuffle(idx)
        half = len(idx) // 2
        assignment.loc[idx[:half]] = "validation"
        assignment.loc[idx[half:]] = "test"
    held_out["split"] = assignment.to_numpy()
    held_out = held_out.set_index("sample_idx")

    combined = pd.concat([train, held_out[["sample_name", "cancer_type", "split"]]])
    if combined.index.duplicated().any():
        raise ValueError("duplicate sample_idx after combining splits")
    combined = combined.reset_index().rename(columns={"index": "sample_idx"})
    if "sample_idx" not in combined.columns:
        combined = combined.rename(columns={combined.columns[0]: "sample_idx"})
    return combined


def build_rna_matrix(sample_universe: pd.DataFrame, output_path: Path) -> dict:
    names = sample_universe.sample_name.tolist()
    frame = pd.read_parquet(GENE_EXPR, columns=names)
    missing = set(names) - set(frame.columns)
    if missing:
        raise ValueError(f"{len(missing)} samples missing from gene expression matrix")
    frame = frame[names].T  # samples x genes
    gene_ids = frame.columns.to_numpy(dtype=str)
    sample_idx = sample_universe.sample_idx.to_numpy(dtype=np.int64)
    values = frame.to_numpy(dtype=np.float32)
    with h5py.File(output_path, "w") as handle:
        # Uncompressed: gzip-chunked HDF5 makes the trainer's per-batch random-row
        # fancy-indexing ~1000x slower (chunk decompression per access dominates).
        handle.create_dataset("X", data=values)
        handle.create_dataset("sample_idx", data=_str_array(sample_idx), dtype=STR_DTYPE)
        handle.create_dataset("gene_ids", data=_str_array(gene_ids), dtype=STR_DTYPE)
    return {"shape": list(values.shape), "path": str(output_path)}


def build_beta_matrix(sample_universe: pd.DataFrame, cpg_universe: pd.DataFrame, output_path: Path) -> dict:
    wanted_cpg = set(int(c) for c in cpg_universe.cpg_idx)
    wanted_sample = set(int(s) for s in sample_universe.sample_idx)
    frames = []
    for part_dir in ME_CPG_BG_DIRS:
        dataset = ds.dataset(part_dir, format="parquet")
        table = dataset.to_table(
            columns=["cpg_idx", "sample_idx", "methylation"],
            filter=(ds.field("cpg_idx").isin(list(wanted_cpg)) & ds.field("sample_idx").isin(list(wanted_sample))),
        )
        frames.append(table.to_pandas())
        print(f"    read {part_dir.name}: {len(frames[-1])} rows", flush=True)
    long = pd.concat(frames, ignore_index=True)
    if long.duplicated(["cpg_idx", "sample_idx"]).any():
        raise ValueError("duplicate (cpg_idx, sample_idx) pairs in beta long table")

    sample_order = sample_universe.sample_idx.to_numpy(dtype=np.int64)
    cpg_order = cpg_universe.cpg_idx.to_numpy(dtype=np.int64)
    sample_pos = {s: i for i, s in enumerate(sample_order.tolist())}
    cpg_pos = {c: i for i, c in enumerate(cpg_order.tolist())}

    dense = np.full((len(sample_order), len(cpg_order)), np.nan, dtype=np.float32)
    rows = long.sample_idx.map(sample_pos).to_numpy()
    cols = long.cpg_idx.map(cpg_pos).to_numpy()
    dense[rows, cols] = long.methylation.to_numpy(np.float32)

    coverage = 1.0 - np.isnan(dense).mean()
    with h5py.File(output_path, "w") as handle:
        handle.create_dataset("beta", data=dense)
        handle.create_dataset("sample_idx", data=_str_array(sample_order), dtype=STR_DTYPE)
        handle.create_dataset("cpg_idx", data=_str_array(cpg_order), dtype=STR_DTYPE)
    return {"shape": list(dense.shape), "coverage": float(coverage), "path": str(output_path)}


def build_embeddings_h5(cpg_universe: pd.DataFrame, embeddings: np.ndarray, output_path: Path) -> dict:
    cpg_idx = cpg_universe.cpg_idx.to_numpy(dtype=np.int64)
    with h5py.File(output_path, "w") as handle:
        handle.create_dataset("embeddings", data=embeddings.astype(np.float32))
        handle.create_dataset("cpg_idx", data=_str_array(cpg_idx), dtype=STR_DTYPE)
    return {"shape": list(embeddings.shape), "path": str(output_path)}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = parser.parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    device = args.device

    print("[1/8] CpG universe + split", flush=True)
    cpg_universe = build_cpg_universe()
    cpg_splits = build_cpg_splits(cpg_universe)
    cpg_splits.to_parquet(output_dir / "cpg_split_manifest.parquet", index=False)

    print("[2/8] NTv3 embeddings", flush=True)
    embeddings = load_embeddings(cpg_universe.cpg_idx.to_numpy())
    embed_info = build_embeddings_h5(cpg_universe, embeddings, output_dir / "locus_embeddings.h5")

    print("[3/8] NTv3 prior (frozen val/test + 5-fold OOF train)", flush=True)
    prior, prior_provenance = build_prior(cpg_universe, cpg_splits, embeddings, device)

    print("[4/8] between-cancer variability", flush=True)
    targets = pd.read_parquet(VARIABILITY_TARGETS, columns=["cpg_idx", "between_cancer_variance", "within_cancer_variance"])
    between, between_provenance = build_variability_component(
        cpg_universe, cpg_splits, embeddings, targets, "between_cancer", BETWEEN_METRICS, device
    )

    print("[5/8] within-cancer variability", flush=True)
    within, within_provenance = build_variability_component(
        cpg_universe, cpg_splits, embeddings, targets, "within_cancer", WITHIN_METRICS, device
    )

    locus_features = pd.DataFrame({
        "cpg_idx": cpg_universe.cpg_idx,
        "pred_ntv3_prior": prior.reindex(cpg_universe.cpg_idx).to_numpy(),
        "pred_log_var_between": between.reindex(cpg_universe.cpg_idx).to_numpy(),
        "pred_log_var_within": within.reindex(cpg_universe.cpg_idx).to_numpy(),
    })
    locus_features.to_parquet(output_dir / "locus_features.parquet", index=False)

    print("[6/8] sample universe + split", flush=True)
    sample_universe = build_sample_universe()
    sample_universe[["sample_idx", "cancer_type", "split"]].to_parquet(output_dir / "sample_metadata.parquet", index=False)

    print("[7/8] RNA matrix", flush=True)
    rna_info = build_rna_matrix(sample_universe, output_dir / "tcga_rna.h5")

    print("[8/8] beta matrix", flush=True)
    beta_info = build_beta_matrix(sample_universe, cpg_universe, output_dir / "tcga_chr1_beta.h5")

    manifest = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "command": "python -m methylation_predictor.rna_branch.prepare_inputs --output-dir " + str(output_dir),
        "cpg_universe": {"n": int(len(cpg_universe)), "chromosome": "chr1", "source": str(CPG_FEATURES)},
        "cpg_split_counts": cpg_splits.split.value_counts().to_dict(),
        "sample_universe": {
            "n": int(len(sample_universe)),
            "split_counts": sample_universe.split.value_counts().to_dict(),
            "n_cancer_types": int(sample_universe.cancer_type.nunique()),
            "official_train_source": str(OFFICIAL_TRAIN_SAMPLES),
            "official_val_source": str(OFFICIAL_VAL_SAMPLES),
            "derived_validation_test_split": {
                "method": "50/50 stratified by cancer_type from the official held-out (val) pool only; official train pool untouched",
                "seed": SAMPLE_VAL_TEST_SPLIT_SEED,
            },
            "dropped_na_cancer_type": True,
        },
        "prior_provenance": prior_provenance,
        "between_cancer_provenance": between_provenance,
        "within_cancer_provenance": within_provenance,
        "rna_matrix": rna_info,
        "beta_matrix": beta_info,
        "embeddings": embed_info,
        "sources_sha256": {
            "cpg_features": sha256(CPG_FEATURES),
            "embeddings_npz": sha256(EMBEDDINGS_NPZ),
            "prior_val_test": sha256(PRIOR_VAL_TEST),
            "variability_targets": sha256(VARIABILITY_TARGETS),
            "sample_cancer_type": sha256(SAMPLE_CANCER_TYPE),
        },
    }
    (output_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str) + "\n")
    print(json.dumps(manifest, indent=2, default=str))


if __name__ == "__main__":
    main()
