base_config: base.yaml
runs:
  - name: linear_bilinear
    override:
      model:
        encoder:
          kind: linear
        interaction:
          kind: bilinear
  - name: mlp_bilinear
    override:
      model:
        encoder:
          kind: mlp
        interaction:
          kind: bilinear
  - name: perceiver_linear_value_bilinear
    override:
      model:
        encoder:
          kind: perceiver
          value_encoding: linear
        interaction:
          kind: bilinear
  - name: perceiver_fourier_bilinear
    override:
      model:
        encoder:
          kind: perceiver
          value_encoding: fourier
        interaction:
          kind: bilinear
