"""Compare splits regenerated by the original preprocessing scripts with audit manifests."""

import hashlib
import json
from pathlib import Path

import pandas as pd
from absl import app, flags


FLAGS = flags.FLAGS
flags.DEFINE_string("audit_split_dir", None, "Directory containing train_cpg/val_cpg/train_sample/val_sample manifests.")
flags.mark_flag_as_required("audit_split_dir")
flags.DEFINE_string("train_cpg_parquet", None, "Train CpG split generated by split_cpg_by_chr.py or split_cpg_by_index_files.py.")
flags.mark_flag_as_required("train_cpg_parquet")
flags.DEFINE_string("val_cpg_parquet", None, "Validation CpG split generated by the original split script.")
flags.mark_flag_as_required("val_cpg_parquet")
flags.DEFINE_string("train_sample_csv", None, "Train sample split generated by the original sample split script.")
flags.mark_flag_as_required("train_sample_csv")
flags.DEFINE_string("val_sample_csv", None, "Validation sample split generated by the original sample split script.")
flags.mark_flag_as_required("val_sample_csv")
flags.DEFINE_string("output_json", None, "Path for the comparison result JSON.")
flags.mark_flag_as_required("output_json")


def read_ids(path, column):
    path = Path(path)
    df = pd.read_parquet(path) if path.suffix == ".parquet" else pd.read_csv(path)
    if column in df.columns:
        values = df[column]
    elif df.index.name == column:
        values = pd.Series(df.index)
    else:
        raise ValueError(f"{path} does not contain {column} as a column or index")
    return pd.Index(values.dropna().unique()).sort_values()


def digest(values):
    hasher = hashlib.sha256()
    for value in values:
        hasher.update(f"{value}\n".encode())
    return hasher.hexdigest()


def compare(name, observed, expected):
    missing = expected.difference(observed)
    unexpected = observed.difference(expected)
    return {
        "name": name,
        "matches": len(missing) == 0 and len(unexpected) == 0,
        "expected_n": len(expected),
        "observed_n": len(observed),
        "expected_sha256": digest(expected),
        "observed_sha256": digest(observed),
        "missing_n": len(missing),
        "unexpected_n": len(unexpected),
    }


def main(_):
    audit_dir = Path(FLAGS.audit_split_dir)
    comparisons = [
        compare("train_cpg", read_ids(FLAGS.train_cpg_parquet, "cpg_idx"), read_ids(audit_dir / "train_cpg.parquet", "cpg_idx")),
        compare("val_cpg", read_ids(FLAGS.val_cpg_parquet, "cpg_idx"), read_ids(audit_dir / "val_cpg.parquet", "cpg_idx")),
        compare(
            "train_sample",
            read_ids(FLAGS.train_sample_csv, "sample_idx"),
            read_ids(audit_dir / "train_sample.parquet", "sample_idx"),
        ),
        compare(
            "val_sample",
            read_ids(FLAGS.val_sample_csv, "sample_idx"),
            read_ids(audit_dir / "val_sample.parquet", "sample_idx"),
        ),
    ]
    result = {"all_match": all(item["matches"] for item in comparisons), "components": comparisons}
    output_path = Path(FLAGS.output_json)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(result, indent=2) + "\n")
    if not result["all_match"]:
        raise ValueError(f"Regenerated splits do not match released prediction manifests: {output_path}")


if __name__ == "__main__":
    app.run(main)
