#!/usr/bin/env python3
"""Pack arbitrary frozen sample embeddings into the RNA-branch HDF5 contract.

Use this adapter for scFoundation, Tahoe-X1, Geneformer, UCE, or layer-wise
embeddings generated by an existing external pipeline.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import h5py
import numpy as np
import pandas as pd


def _load_array(path: Path, key: str | None) -> np.ndarray:
    if path.suffix.lower() == ".npy":
        return np.load(path, allow_pickle=False)
    if path.suffix.lower() == ".npz":
        archive = np.load(path, allow_pickle=False)
        if key is None:
            if len(archive.files) != 1:
                raise ValueError(f"--embeddings-key is required; available keys: {archive.files}")
            key = archive.files[0]
        return archive[key]
    raise ValueError("embeddings must be .npy or .npz")


def _load_ids(path: Path, column: str | None) -> np.ndarray:
    if path.suffix.lower() == ".npy":
        return np.load(path, allow_pickle=False).astype(str)
    if path.suffix.lower() == ".npz":
        archive = np.load(path, allow_pickle=False)
        if column is None:
            if len(archive.files) != 1:
                raise ValueError(f"--sample-id-column is required; available keys: {archive.files}")
            column = archive.files[0]
        return archive[column].astype(str)
    frame = pd.read_csv(path, sep="\t" if path.suffix.lower() in {".tsv", ".txt"} else ",")
    if column is None:
        if len(frame.columns) != 1:
            raise ValueError(f"--sample-id-column is required; available columns: {frame.columns.tolist()}")
        column = frame.columns[0]
    return frame[column].astype(str).to_numpy()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--embeddings", required=True)
    parser.add_argument("--embeddings-key")
    parser.add_argument("--sample-ids", required=True)
    parser.add_argument("--sample-id-column")
    parser.add_argument("--output", required=True)
    parser.add_argument("--encoder-name", required=True)
    parser.add_argument("--checkpoint", default="unknown")
    parser.add_argument("--layer", default="unknown")
    parser.add_argument("--pooling", default="unknown")
    parser.add_argument("--metadata-json", help="optional JSON object merged into sidecar metadata")
    args = parser.parse_args()

    embeddings = np.asarray(_load_array(Path(args.embeddings), args.embeddings_key), dtype=np.float32)
    sample_ids = _load_ids(Path(args.sample_ids), args.sample_id_column)
    if embeddings.ndim != 2:
        raise ValueError(f"embeddings must be 2-D, got {embeddings.shape}")
    if len(sample_ids) != len(embeddings):
        raise ValueError(f"sample IDs ({len(sample_ids)}) != embeddings ({len(embeddings)})")
    if len(set(sample_ids.tolist())) != len(sample_ids):
        raise ValueError("sample IDs must be unique")
    if not np.isfinite(embeddings).all():
        raise ValueError("embeddings contain NaN/Inf")

    metadata: dict[str, object] = {
        "encoder": args.encoder_name,
        "checkpoint": args.checkpoint,
        "layer": args.layer,
        "pooling": args.pooling,
        "n_samples": int(len(sample_ids)),
        "embedding_dim": int(embeddings.shape[1]),
    }
    if args.metadata_json:
        metadata.update(json.loads(args.metadata_json))

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    strings = h5py.string_dtype(encoding="utf-8")
    with h5py.File(output, "w") as handle:
        handle.create_dataset("embeddings", data=embeddings)
        handle.create_dataset("sample_idx", data=np.asarray(sample_ids, dtype=object), dtype=strings)
        handle.create_dataset(
            "feature_ids",
            data=np.asarray([f"feature_{index}" for index in range(embeddings.shape[1])], dtype=object),
            dtype=strings,
        )
        for key, value in metadata.items():
            handle.attrs[key] = json.dumps(value) if isinstance(value, (dict, list, tuple)) else value
    output.with_suffix(output.suffix + ".json").write_text(json.dumps(metadata, indent=2, sort_keys=True))
    print(json.dumps(metadata, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
